on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile app.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
